[package]
name = "reference-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
imagesize.workspace = true
image.workspace = true
libc.workspace = true
reference-protocol = { path = "../reference-protocol" }
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
serde_json.workspace = true

[[bin]]
name = "reference-core"
path = "src/main.rs"
